### ISSUE TITLE
You should change your twitter password 

### ISSUE THREAD

**Issue by hendrik-boe** [Rudyg810/--twitter--#1]
https://github.com/Rudyg810/Twitter-Tweet-Handeller/blob/06a2b12eaf6b6e4e1a94ce5660f88d0444c30263/backend/script.js#L10

**Comment by Rudyg810** [comment]
Yeah I know, I didn't think anyone would even use that thing, How did you even come across this repository, It doesn't even contain valuable

**Comment by hendrik-boe** [comment]
Just scrolling through Github searching for Twitter Endpoints

**Comment by Rudyg810** [comment]
there is one in python Twitter API
https://pypi.org/project/twitter
Its a core level scrapers pretty decent but uses your creds

Or you can directly just go to rapid API free version 500 requests are given, make multiple ids and boom,
its way reliable
